// Writes src/environments/version.ts: this build's version (the root package.json) and the
// short SHA of the commit it is built from, for the footer and for `session.json`'s `app`
// field (docs/DATA-MODEL.md). npm runs it after `npm install` and before `npm start` and
// `npm run build` (apps/web/package.json); the file is generated, so it is not committed.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const appDir = resolve(import.meta.dirname, '..');
const target = resolve(appDir, 'src/environments/version.ts');

function rootVersion(): string {
  const text = readFileSync(resolve(appDir, '../../package.json'), 'utf8');
  const parsed: unknown = JSON.parse(text);
  if (typeof parsed === 'object' && parsed !== null && 'version' in parsed) {
    const { version } = parsed;
    if (typeof version === 'string') {
      return version;
    }
  }
  throw new Error('The root package.json has no "version".');
}

function shortCommit(): string {
  try {
    return execFileSync('git', ['rev-parse', '--short=7', 'HEAD'], {
      cwd: appDir,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    // Not a git checkout (a source archive) or no git on the machine.
    return 'unknown';
  }
}

const source = `// Generated by scripts/write-version.mts; not committed (docs/TOOLCHAIN.md). Do not edit.

/** This build: the version of the root package.json and the short SHA of its commit. */
export const APP_BUILD: { readonly version: string; readonly commit: string } = {
  version: ${JSON.stringify(rootVersion())},
  commit: ${JSON.stringify(shortCommit())},
};
`;

// Rewriting an unchanged file would make a running `ng serve` rebuild for nothing.
if (!existsSync(target) || readFileSync(target, 'utf8') !== source) {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, source);
}
